# Generated by Django 5.0.3 on 2024-07-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_orders_created_at_alter_orders_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
