# Generated by Django 5.0.3 on 2024-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_rename_user_id_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='created', max_length=15),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
